---
- name: Prepare configuration directory for ivynet
  ansible.builtin.file:
    path: "/home/ivynet/.ivynet"
    state: directory
    owner: "{{ ivynet_client_user }}"
    group: "{{ ivynet_client_group }}"
    mode: "0755"
  tags:
    - ivynet_client
    - systemd

- name: Copy Client Service file
  ansible.builtin.template:
    src: ivynet-client.service.j2
    dest: /etc/systemd/system/ivynet-client.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload daemon
    - Restart client service
  tags:
    - ivynet_client
    - systemd

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set Client service
  ansible.builtin.systemd_service:
    name: ivynet-client
    state: started
    enabled: true
    daemon_reload: true
  when:
    - "'ivynet-client.service' not in services"
  tags:
    - ivynet_client
    - systemd
