---
- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart client service
  ansible.builtin.systemd_service:
    name: ivynet-client
    state: restarted
    enabled: true
