---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu24.04
    image: ubuntu:noble
  - name: ubuntu22.04
    image: ubuntu:jammy
  - name: debian12
    image: debian:bookworm
  - name: rocky9
    image: rockylinux:9
  - name: fedora
    image: fedora:40
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      fact_caching_timeout: 86400
      remote_tmp: /tmp
verifier:
  name: ansible
