---
- name: Verify
  hosts: all
  vars:
    ivynet_client_path: /opt/ivynet/bin/ivynet
  tasks:
    - name: Get file stats
      ansible.builtin.stat:
        path: "{{ ivynet_client_path }}"
      register:
        ivynet_bin
    - name: Show
      ansible.builtin.debug:
        msg: "{{ ivynet_bin }}"
    - name: Assert that the file is downloaded
      ansible.builtin.assert:
        that:
          - ivynet_bin.stat.isreg is defined
          - ivynet_bin.stat.isreg == True
          - ivynet_bin.stat.size > 2**20
    - name: Check if version printed out
      ansible.builtin.shell:
        cmd: |
          set -o pipefail &&
          {{ ivynet_client_path }} -V |
          grep -qE "ivy\ [0-9]+(\.[0-9]+){2}"
        executable: /bin/bash
      register:
        ivynet_version_check
      changed_when: ivynet_version_check.rc != 0
    - name: Assert that the binary starts successfully
      ansible.builtin.assert:
        that:
          - ivynet_version_check.rc == 0
