---
name: Run Molecule

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
